languages:
  Python: true

exclude_paths:
- "Trakttv.bundle/Contents/Libraries/Shared/arrow/*"
- "Trakttv.bundle/Contents/Libraries/Shared/asio/*"
- "Trakttv.bundle/Contents/Libraries/Shared/caper/*"
- "Trakttv.bundle/Contents/Libraries/Shared/concurrent/*"
- "Trakttv.bundle/Contents/Libraries/Shared/expiringdict/*"
- "Trakttv.bundle/Contents/Libraries/Shared/jsonpickle/*"
- "Trakttv.bundle/Contents/Libraries/Shared/logr/*"
- "Trakttv.bundle/Contents/Libraries/Shared/msgpack/*"
- "Trakttv.bundle/Contents/Libraries/Shared/multiprocessing/*"
- "Trakttv.bundle/Contents/Libraries/Shared/peewee_migrate/*"
- "Trakttv.bundle/Contents/Libraries/Shared/playhouse/*"
- "Trakttv.bundle/Contents/Libraries/Shared/plex/*"
- "Trakttv.bundle/Contents/Libraries/Shared/plex_activity/*"
- "Trakttv.bundle/Contents/Libraries/Shared/plex_database/*"
- "Trakttv.bundle/Contents/Libraries/Shared/plex_metadata/*"
- "Trakttv.bundle/Contents/Libraries/Shared/pyllist/*"
- "Trakttv.bundle/Contents/Libraries/Shared/pytz/*"
- "Trakttv.bundle/Contents/Libraries/Shared/raven/*"
- "Trakttv.bundle/Contents/Libraries/Shared/requests/*"
- "Trakttv.bundle/Contents/Libraries/Shared/shove/*"
- "Trakttv.bundle/Contents/Libraries/Shared/stash/*"
- "Trakttv.bundle/Contents/Libraries/Shared/stuf/*"
- "Trakttv.bundle/Contents/Libraries/Shared/trakt/*"
- "Trakttv.bundle/Contents/Libraries/Shared/trakt_sync/*"
- "Trakttv.bundle/Contents/Libraries/Shared/tzlocal/*"
- "Trakttv.bundle/Contents/Libraries/Shared/ago.py"
- "Trakttv.bundle/Contents/Libraries/Shared/ipaddress.py"
- "Trakttv.bundle/Contents/Libraries/Shared/itsdangerous.py"
- "Trakttv.bundle/Contents/Libraries/Shared/peewee.py"
- "Trakttv.bundle/Contents/Libraries/Shared/pyemitter.py"
- "Trakttv.bundle/Contents/Libraries/Shared/six.py"
- "Trakttv.bundle/Contents/Libraries/Shared/websocket.py"