from __future__ import absolute_import

from exception_wrappers.exceptions import ModuleDisabledError
from exception_wrappers.manager import ExceptionSource, ExceptionWrapper
import logging
import sys


exw_enabled = False

exw_exception = None
exw_exc_info = (None, None, None)

# Try import "apsw", generate skeleton if an error is raised
try:
    from apsw import *

    exw_enabled = True
except ImportError as ex:
    # Emit event
    ExceptionWrapper.add(ExceptionSource.APSW, sys.exc_info(), 'apsw')

    # Update module state
    exw_exception = ex
    exw_exc_info = sys.exc_info()

    # Generate skeleton cursor class
    class Cursor(object):
        lastrowid = 0
        rowcount = 0

        def execute(self, *args, **kwargs):
            raise ModuleDisabledError(exw_exception)

        def fetchone(self, *args, **kwargs):
            raise ModuleDisabledError(exw_exception)

        def close(self, *args, **kwargs):
            raise ModuleDisabledError(exw_exception)

    # Generate skeleton connection class
    class Connection(object):
        def __init__(self, *args, **kwargs):
            pass

        def cursor(self, *args, **kwargs):
            return Cursor()

        def commit(self, *args, **kwargs):
            raise ModuleDisabledError(exw_exception)

        def rollback(self, *args, **kwargs):
            raise ModuleDisabledError(exw_exception)

        def setbusytimeout(self, *args, **kwargs):
            raise ModuleDisabledError(exw_exception)

    # Generate skeleton exception classes
    class Error(Exception):
        pass

    class CantOpenError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class ConstraintError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class CorruptError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class FullError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class IOError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class NotADBError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class PermissionsError(Error):
        def __init__(self, *args, **kwargs):
            pass

    class ReadOnlyError(Error):
        def __init__(self, *args, **kwargs):
            pass

    # Variables with simple values
    SQLITE_ABORT = 4

    SQLITE_ABORT_ROLLBACK = 516

    SQLITE_ACCESS_EXISTS = 0
    SQLITE_ACCESS_READ = 2
    SQLITE_ACCESS_READWRITE = 1

    SQLITE_ALTER_TABLE = 26

    SQLITE_ANALYZE = 28
    SQLITE_ATTACH = 24
    SQLITE_AUTH = 23

    SQLITE_AUTH_USER = 279

    SQLITE_BUSY = 5

    SQLITE_BUSY_RECOVERY = 261
    SQLITE_BUSY_SNAPSHOT = 517

    SQLITE_CANTOPEN = 14

    SQLITE_CANTOPEN_CONVPATH = 1038
    SQLITE_CANTOPEN_FULLPATH = 782
    SQLITE_CANTOPEN_ISDIR = 526
    SQLITE_CANTOPEN_NOTEMPDIR = 270

    SQLITE_CHECKPOINT_FULL = 1
    SQLITE_CHECKPOINT_PASSIVE = 0
    SQLITE_CHECKPOINT_RESTART = 2
    SQLITE_CHECKPOINT_TRUNCATE = 3

    SQLITE_CONFIG_COVERING_INDEX_SCAN = 20

    SQLITE_CONFIG_GETMALLOC = 5
    SQLITE_CONFIG_GETMUTEX = 11
    SQLITE_CONFIG_GETPCACHE = 15
    SQLITE_CONFIG_GETPCACHE2 = 19
    SQLITE_CONFIG_HEAP = 8
    SQLITE_CONFIG_LOG = 16
    SQLITE_CONFIG_LOOKASIDE = 13
    SQLITE_CONFIG_MALLOC = 4
    SQLITE_CONFIG_MEMSTATUS = 9

    SQLITE_CONFIG_MMAP_SIZE = 22

    SQLITE_CONFIG_MULTITHREAD = 2
    SQLITE_CONFIG_MUTEX = 10
    SQLITE_CONFIG_PAGECACHE = 7
    SQLITE_CONFIG_PCACHE = 14
    SQLITE_CONFIG_PCACHE2 = 18

    SQLITE_CONFIG_PCACHE_HDRSZ = 24

    SQLITE_CONFIG_PMASZ = 25
    SQLITE_CONFIG_SCRATCH = 6
    SQLITE_CONFIG_SERIALIZED = 3
    SQLITE_CONFIG_SINGLETHREAD = 1
    SQLITE_CONFIG_SQLLOG = 21

    SQLITE_CONFIG_STMTJRNL_SPILL = 26

    SQLITE_CONFIG_URI = 17

    SQLITE_CONFIG_WIN32_HEAPSIZE = 23

    SQLITE_CONSTRAINT = 19

    SQLITE_CONSTRAINT_CHECK = 275
    SQLITE_CONSTRAINT_COMMITHOOK = 531
    SQLITE_CONSTRAINT_FOREIGNKEY = 787
    SQLITE_CONSTRAINT_FUNCTION = 1043
    SQLITE_CONSTRAINT_NOTNULL = 1299
    SQLITE_CONSTRAINT_PRIMARYKEY = 1555
    SQLITE_CONSTRAINT_ROWID = 2579
    SQLITE_CONSTRAINT_TRIGGER = 1811
    SQLITE_CONSTRAINT_UNIQUE = 2067
    SQLITE_CONSTRAINT_VTAB = 2323

    SQLITE_COPY = 0
    SQLITE_CORRUPT = 11

    SQLITE_CORRUPT_VTAB = 267

    SQLITE_CREATE_INDEX = 1
    SQLITE_CREATE_TABLE = 2

    SQLITE_CREATE_TEMP_INDEX = 3
    SQLITE_CREATE_TEMP_TABLE = 4
    SQLITE_CREATE_TEMP_TRIGGER = 5
    SQLITE_CREATE_TEMP_VIEW = 6

    SQLITE_CREATE_TRIGGER = 7
    SQLITE_CREATE_VIEW = 8
    SQLITE_CREATE_VTABLE = 29

    SQLITE_DBCONFIG_ENABLE_FKEY = 1002

    SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004

    SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005

    SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003

    SQLITE_DBCONFIG_LOOKASIDE = 1001

    SQLITE_DBSTATUS_CACHE_HIT = 7
    SQLITE_DBSTATUS_CACHE_MISS = 8
    SQLITE_DBSTATUS_CACHE_USED = 1
    SQLITE_DBSTATUS_CACHE_WRITE = 9

    SQLITE_DBSTATUS_DEFERRED_FKS = 10

    SQLITE_DBSTATUS_LOOKASIDE_HIT = 4

    SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL = 6
    SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE = 5

    SQLITE_DBSTATUS_LOOKASIDE_USED = 0

    SQLITE_DBSTATUS_MAX = 10

    SQLITE_DBSTATUS_SCHEMA_USED = 2

    SQLITE_DBSTATUS_STMT_USED = 3

    SQLITE_DELETE = 9
    SQLITE_DENY = 1
    SQLITE_DETACH = 25
    SQLITE_DONE = 101

    SQLITE_DROP_INDEX = 10
    SQLITE_DROP_TABLE = 11

    SQLITE_DROP_TEMP_INDEX = 12
    SQLITE_DROP_TEMP_TABLE = 13
    SQLITE_DROP_TEMP_TRIGGER = 14
    SQLITE_DROP_TEMP_VIEW = 15

    SQLITE_DROP_TRIGGER = 16
    SQLITE_DROP_VIEW = 17
    SQLITE_DROP_VTABLE = 30

    SQLITE_EMPTY = 16
    SQLITE_ERROR = 1
    SQLITE_FAIL = 3

    SQLITE_FCNTL_BUSYHANDLER = 15

    SQLITE_FCNTL_CHUNK_SIZE = 6

    SQLITE_FCNTL_COMMIT_PHASETWO = 22

    SQLITE_FCNTL_FILE_POINTER = 7

    SQLITE_FCNTL_GET_LOCKPROXYFILE = 2

    SQLITE_FCNTL_HAS_MOVED = 20

    SQLITE_FCNTL_JOURNAL_POINTER = 28

    SQLITE_FCNTL_LAST_ERRNO = 4

    SQLITE_FCNTL_LOCKSTATE = 1

    SQLITE_FCNTL_MMAP_SIZE = 18

    SQLITE_FCNTL_OVERWRITE = 11

    SQLITE_FCNTL_PERSIST_WAL = 10

    SQLITE_FCNTL_POWERSAFE_OVERWRITE = 13

    SQLITE_FCNTL_PRAGMA = 14
    SQLITE_FCNTL_RBU = 26

    SQLITE_FCNTL_SET_LOCKPROXYFILE = 3

    SQLITE_FCNTL_SIZE_HINT = 5

    SQLITE_FCNTL_SYNC = 21

    SQLITE_FCNTL_SYNC_OMITTED = 8

    SQLITE_FCNTL_TEMPFILENAME = 16
    SQLITE_FCNTL_TRACE = 19
    SQLITE_FCNTL_VFSNAME = 12

    SQLITE_FCNTL_VFS_POINTER = 27

    SQLITE_FCNTL_WAL_BLOCK = 24

    SQLITE_FCNTL_WIN32_AV_RETRY = 9

    SQLITE_FCNTL_WIN32_SET_HANDLE = 23

    SQLITE_FCNTL_ZIPVFS = 25

    SQLITE_FORMAT = 24
    SQLITE_FULL = 13
    SQLITE_FUNCTION = 31
    SQLITE_IGNORE = 2

    SQLITE_INDEX_CONSTRAINT_EQ = 2
    SQLITE_INDEX_CONSTRAINT_GE = 32
    SQLITE_INDEX_CONSTRAINT_GLOB = 66
    SQLITE_INDEX_CONSTRAINT_GT = 4
    SQLITE_INDEX_CONSTRAINT_LE = 8
    SQLITE_INDEX_CONSTRAINT_LIKE = 65
    SQLITE_INDEX_CONSTRAINT_LT = 16
    SQLITE_INDEX_CONSTRAINT_MATCH = 64
    SQLITE_INDEX_CONSTRAINT_REGEXP = 67

    SQLITE_INDEX_SCAN_UNIQUE = 1

    SQLITE_INSERT = 18
    SQLITE_INTERNAL = 2
    SQLITE_INTERRUPT = 9

    SQLITE_IOCAP_ATOMIC = 1
    SQLITE_IOCAP_ATOMIC16K = 64
    SQLITE_IOCAP_ATOMIC1K = 4
    SQLITE_IOCAP_ATOMIC2K = 8
    SQLITE_IOCAP_ATOMIC32K = 128
    SQLITE_IOCAP_ATOMIC4K = 16
    SQLITE_IOCAP_ATOMIC512 = 2
    SQLITE_IOCAP_ATOMIC64K = 256
    SQLITE_IOCAP_ATOMIC8K = 32
    SQLITE_IOCAP_IMMUTABLE = 8192

    SQLITE_IOCAP_POWERSAFE_OVERWRITE = 4096

    SQLITE_IOCAP_SAFE_APPEND = 512

    SQLITE_IOCAP_SEQUENTIAL = 1024

    SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN = 2048

    SQLITE_IOERR = 10

    SQLITE_IOERR_ACCESS = 3338
    SQLITE_IOERR_AUTH = 7178
    SQLITE_IOERR_BLOCKED = 2826
    SQLITE_IOERR_CHECKRESERVEDLOCK = 3594
    SQLITE_IOERR_CLOSE = 4106
    SQLITE_IOERR_CONVPATH = 6666
    SQLITE_IOERR_DELETE = 2570

    SQLITE_IOERR_DELETE_NOENT = 5898

    SQLITE_IOERR_DIR_CLOSE = 4362
    SQLITE_IOERR_DIR_FSYNC = 1290

    SQLITE_IOERR_FSTAT = 1802
    SQLITE_IOERR_FSYNC = 1034
    SQLITE_IOERR_GETTEMPPATH = 6410
    SQLITE_IOERR_LOCK = 3850
    SQLITE_IOERR_MMAP = 6154
    SQLITE_IOERR_NOMEM = 3082
    SQLITE_IOERR_RDLOCK = 2314
    SQLITE_IOERR_READ = 266
    SQLITE_IOERR_SEEK = 5642
    SQLITE_IOERR_SHMLOCK = 5130
    SQLITE_IOERR_SHMMAP = 5386
    SQLITE_IOERR_SHMOPEN = 4618
    SQLITE_IOERR_SHMSIZE = 4874

    SQLITE_IOERR_SHORT_READ = 522

    SQLITE_IOERR_TRUNCATE = 1546
    SQLITE_IOERR_UNLOCK = 2058
    SQLITE_IOERR_VNODE = 6922
    SQLITE_IOERR_WRITE = 778

    SQLITE_LIMIT_ATTACHED = 7
    SQLITE_LIMIT_COLUMN = 2

    SQLITE_LIMIT_COMPOUND_SELECT = 4

    SQLITE_LIMIT_EXPR_DEPTH = 3

    SQLITE_LIMIT_FUNCTION_ARG = 6

    SQLITE_LIMIT_LENGTH = 0

    SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8

    SQLITE_LIMIT_SQL_LENGTH = 1

    SQLITE_LIMIT_TRIGGER_DEPTH = 10

    SQLITE_LIMIT_VARIABLE_NUMBER = 9

    SQLITE_LIMIT_VDBE_OP = 5

    SQLITE_LIMIT_WORKER_THREADS = 11

    SQLITE_LOCKED = 6

    SQLITE_LOCKED_SHAREDCACHE = 262

    SQLITE_LOCK_EXCLUSIVE = 4
    SQLITE_LOCK_NONE = 0
    SQLITE_LOCK_PENDING = 3
    SQLITE_LOCK_RESERVED = 2
    SQLITE_LOCK_SHARED = 1

    SQLITE_MISMATCH = 20
    SQLITE_MISUSE = 21
    SQLITE_NOLFS = 22
    SQLITE_NOMEM = 7
    SQLITE_NOTADB = 26
    SQLITE_NOTFOUND = 12
    SQLITE_NOTICE = 27

    SQLITE_NOTICE_RECOVER_ROLLBACK = 539
    SQLITE_NOTICE_RECOVER_WAL = 283

    SQLITE_OK = 0

    SQLITE_OPEN_AUTOPROXY = 32
    SQLITE_OPEN_CREATE = 4
    SQLITE_OPEN_DELETEONCLOSE = 8
    SQLITE_OPEN_EXCLUSIVE = 16
    SQLITE_OPEN_FULLMUTEX = 65536

    SQLITE_OPEN_MAIN_DB = 256
    SQLITE_OPEN_MAIN_JOURNAL = 2048

    SQLITE_OPEN_MASTER_JOURNAL = 16384

    SQLITE_OPEN_MEMORY = 128
    SQLITE_OPEN_NOMUTEX = 32768
    SQLITE_OPEN_PRIVATECACHE = 262144
    SQLITE_OPEN_READONLY = 1
    SQLITE_OPEN_READWRITE = 2
    SQLITE_OPEN_SHAREDCACHE = 131072
    SQLITE_OPEN_SUBJOURNAL = 8192

    SQLITE_OPEN_TEMP_DB = 512
    SQLITE_OPEN_TEMP_JOURNAL = 4096

    SQLITE_OPEN_TRANSIENT_DB = 1024

    SQLITE_OPEN_URI = 64
    SQLITE_OPEN_WAL = 524288

    SQLITE_PERM = 3
    SQLITE_PRAGMA = 19
    SQLITE_PROTOCOL = 15
    SQLITE_RANGE = 25
    SQLITE_READ = 20
    SQLITE_READONLY = 8

    SQLITE_READONLY_CANTLOCK = 520
    SQLITE_READONLY_DBMOVED = 1032
    SQLITE_READONLY_RECOVERY = 264
    SQLITE_READONLY_ROLLBACK = 776

    SQLITE_RECURSIVE = 33
    SQLITE_REINDEX = 27
    SQLITE_REPLACE = 5
    SQLITE_ROLLBACK = 1
    SQLITE_ROW = 100
    SQLITE_SAVEPOINT = 32
    SQLITE_SCHEMA = 17
    SQLITE_SELECT = 21

    SQLITE_SHM_EXCLUSIVE = 8
    SQLITE_SHM_LOCK = 2
    SQLITE_SHM_SHARED = 4
    SQLITE_SHM_UNLOCK = 1

    SQLITE_STATUS_MALLOC_COUNT = 9
    SQLITE_STATUS_MALLOC_SIZE = 5

    SQLITE_STATUS_MEMORY_USED = 0

    SQLITE_STATUS_PAGECACHE_OVERFLOW = 2
    SQLITE_STATUS_PAGECACHE_SIZE = 7
    SQLITE_STATUS_PAGECACHE_USED = 1

    SQLITE_STATUS_PARSER_STACK = 6

    SQLITE_STATUS_SCRATCH_OVERFLOW = 4
    SQLITE_STATUS_SCRATCH_SIZE = 8
    SQLITE_STATUS_SCRATCH_USED = 3

    SQLITE_SYNC_DATAONLY = 16
    SQLITE_SYNC_FULL = 3
    SQLITE_SYNC_NORMAL = 2

    SQLITE_TOOBIG = 18
    SQLITE_TRANSACTION = 22
    SQLITE_UPDATE = 23

    SQLITE_VERSION_NUMBER = 3013000

    SQLITE_VTAB_CONSTRAINT_SUPPORT = 1

    SQLITE_WARNING = 28

    SQLITE_WARNING_AUTOINDEX = 284
